[project]
name = "ip-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncer>=0.0.10",
    "fastmcp>=2.13.0.2",
    "oracledb>=3.4.0",
    "python-dotenv>=1.2.1",
]
